IT-3448: procedure to simplify listing file downloaders
Sage-Bionetworks/snowflake pull request #27
Opened 2024-02-28 16:43 UTC by xschildw

This PR creates a procedure to simplify list who dowloaded files within one or more subtrees.

Example: 'call list_downloaders('2021-01-01', '25982471')

Returns a table:
|USER_ID|USER_NAME|EMAIL|SYNAPSE_PROFILE|NUM_DOWNLOADS|EARLIEST_DOWNLOAD_TIME|LATEST_DOWNLOAD_TIME|
|---------|-------------|------|--------------------|--------------------|-------------------------------|-------------------|
|1223456|myUser|myuser@myDomain.com|https://www.synapse.org/#!Profile:123456|10|2023-01-14 12:01:00|2023-02-01 01:00:04|

2024-02-28 16:53 UTC, thomasyu888 commented on synapse_data_warehouse/synapse/procs/R2.13.0__add_list_downloaders.sql
> +CREATE OR REPLACE PROCEDURE list_downloaders(start_record_date string, entity_list string)
Could we use the `DATE` type here?  string is also fine, but you can do something like

`record_date > DATE('2024-02-16')`

2024-02-28 16:53 UTC, thomasyu888 commented on synapse_data_warehouse/synapse/procs/R2.13.0__add_list_downloaders.sql
> +    select user_id, count(*) as c, min(timestamp) as min_t, max(timestamp) as max_t
The number of downloads here isn't de-duplicated.  A download is considered as 

```
select distinct user_id, record_date, file_handle_id from synapse_data_warehouse.synapse.filedownload
```

2024-02-28 16:53 UTC, thomasyu888 commented on synapse_data_warehouse/synapse/procs/R2.13.0__add_list_downloaders.sql
> +    from filedownload fd
So to use this function, I assume you have to do:

```
USE SCHEMA synapse_data_warehouse.synapse # or ...dev.synapse
```

Is that right?

2025-01-31 19:16 UTC, BryanFauble commented on synapse_data_warehouse/synapse/procs/R2.13.0__add_list_downloaders.sql
> +CREATE OR REPLACE PROCEDURE list_downloaders(start_record_date string, entity_list string)
+1

2025-01-31 19:30 UTC, BryanFauble commented on synapse_data_warehouse/synapse/procs/R2.13.0__add_list_downloaders.sql
> +    join filetree ft on ft.id = fd.association_object_id
`node_latest` only contains the entities that have a Synapse ID, however, files stored within a table that have a column type of `File` don't have Synapse IDs. These only have the ID of the file handle, and that file handle ID is attached to the table through a `filehandleassociation` table [(See this related Jira ticket)](https://sagebionetworks.jira.com/browse/PLFM-8336)

Suppose I wanted to get download statistics for one or more of these kinds of files, should this be supported in this stored procedure?

Phrased another way: 
Given a table in Synapse that contains a column of type `File`, suppose I want to retrieve the stats on the downloads for one or more rows in that table. Is there (Or should there be) a stored procedure for this functionality?

2025-01-31 19:31 UTC, BryanFauble requested changes
Take a look over the comments when you get a chance. Thanks for the changes Xa

2025-02-05 22:36 UTC, philerooski commented
I see a couple of stored procedures which already exist in SYNAPSE_DATA_WAREHOUSE.SYNAPSE that look similar to what we're trying to merge here. Were those procedures created "off the books" (there's no record of their creation in schemachange) and this PR is meant to put one of those procedures back on the books?

<img width="439" alt="image" src="https://github.com/user-attachments/assets/44df9d94-09fd-469c-a087-5663bd296fa2" />

2025-02-06 04:22 UTC, thomasyu888 commented
> Were those procedures created "off the books" (there's no record of their creation in schemachange) and this PR is meant to put one of those procedures back on the books?

I think that is what happened.  @xschildw created these with his SYSADMIN account directly in the warehouse and then backfilled this PR.  This is the first stored procedure to be added through schemachange.  @philerooski i wonder if we can create a Jira ticket to finalize this.

2025-06-02 18:25 UTC, closed without merging